Docker Compose is now in the Docker CLI, try `docker compose up`

Attaching to api-note_api_1, api-note_tests_1
[36mapi_1    |[0m npm install
[33mtests_1  |[0m waiting for server...
[33mtests_1  |[0m npx: installed 13 in 11.813s
[36mapi_1    |[0m npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
[36mapi_1    |[0m npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[36mapi_1    |[0m 
[36mapi_1    |[0m audited 506 packages in 21.739s
[36mapi_1    |[0m 
[36mapi_1    |[0m 66 packages are looking for funding
[36mapi_1    |[0m   run `npm fund` for details
[36mapi_1    |[0m 
[36mapi_1    |[0m found 0 vulnerabilities
[36mapi_1    |[0m 
[36mapi_1    |[0m npm start
[36mapi_1    |[0m npx: installed 175 in 22.751s
[36mapi_1    |[0m 
[36mapi_1    |[0m                         -------------
[36mapi_1    |[0m 
[36mapi_1    |[0m __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
[36mapi_1    |[0m  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
[36mapi_1    |[0m   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
[36mapi_1    |[0m    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
[36mapi_1    |[0m     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
[36mapi_1    |[0m      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
[36mapi_1    |[0m       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
[36mapi_1    |[0m        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
[36mapi_1    |[0m         _\///______________\///______________\///__\///////////////__
[36mapi_1    |[0m 
[36mapi_1    |[0m 
[36mapi_1    |[0m                           Runtime Edition
[36mapi_1    |[0m 
[36mapi_1    |[0m         PM2 is a Production Process Manager for Node.js applications
[36mapi_1    |[0m                      with a built-in Load Balancer.
[36mapi_1    |[0m 
[36mapi_1    |[0m                 Start and Daemonize any application:
[36mapi_1    |[0m                 $ pm2 start app.js
[36mapi_1    |[0m 
[36mapi_1    |[0m                 Load Balance 4 instances of api.js:
[36mapi_1    |[0m                 $ pm2 start api.js -i 4
[36mapi_1    |[0m 
[36mapi_1    |[0m                 Monitor in production:
[36mapi_1    |[0m                 $ pm2 monitor
[36mapi_1    |[0m 
[36mapi_1    |[0m                 Make pm2 auto-boot at server restart:
[36mapi_1    |[0m                 $ pm2 startup
[36mapi_1    |[0m 
[36mapi_1    |[0m                 To go further checkout:
[36mapi_1    |[0m                 http://pm2.io/
[36mapi_1    |[0m 
[36mapi_1    |[0m 
[36mapi_1    |[0m                         -------------
[36mapi_1    |[0m 
[36mapi_1    |[0m pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: Launching in no daemon mode
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: [PM2] Starting /home/node/app/server.js in fork_mode (1 instance)
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: App [server:0] starting in -fork mode-
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: App [server:0] online
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: [PM2] Done.
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: ┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
[36mapi_1    |[0m │ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
[36mapi_1    |[0m ├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
[36mapi_1    |[0m │ 0   │ server    │ default     │ 1.0.0   │ fork    │ 52       │ 0s     │ 0    │ online    │ 0%       │ 32.3mb   │ node     │ disabled │
[36mapi_1    |[0m └─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: [--no-daemon] Continue to stream logs
[36mapi_1    |[0m 2021-04-26T15:51:45: PM2 log: [--no-daemon] Exit on target PM2 exit pid=1
[36mapi_1    |[0m 15:51:55 0|server  | Successfully connected to MongoDB client
[36mapi_1    |[0m 15:51:55 0|server  | App listening on PORT 3000
[33mtests_1  |[0m starting tests...
[33mtests_1  |[0m 
[33mtests_1  |[0m ℹ️ Testing API in end-to-end mode.
[33mtests_1  |[0m WARNING: These tests will clear the database mongodb://mongo:27017
[33mtests_1  |[0m   ✔ 1-golden-path › POST /signup - returns a token (250ms)
[33mtests_1  |[0m   ✔ 1-golden-path › POST /signup - returns a null error
[33mtests_1  |[0m   ✔ 1-golden-path › POST /signup - returns a status 200
[33mtests_1  |[0m   ✖ 1-golden-path › POST /signin on an existing user - returns a token 
[33mtests_1  |[0m   ✖ 1-golden-path › POST /signin on an existing user - returns a null error 
[33mtests_1  |[0m   ✖ 1-golden-path › POST /signin on an existing user - returns a status 200 
[33mtests_1  |[0m   ✔ 1-golden-path › GET /notes of new user - returns empty array (115ms)
[33mtests_1  |[0m   ✔ 1-golden-path › GET /notes of new user - returns a null error (108ms)
[33mtests_1  |[0m   ✔ 1-golden-path › GET /notes of new user - returns a status 200 (121ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PUT /notes - returns a null error (123ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PUT /notes - returns a status 200 (126ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PUT /notes - returns the note with its content (119ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PUT /notes - adds a note (126ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PUT /notes - adds a note that has an _id (133ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PATCH /notes/:id - returns a null error (144ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PATCH /notes/:id - returns a status 200 (132ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PATCH /notes/:id - returns the note and its content (126ms)
[33mtests_1  |[0m   ✔ 1-golden-path › PATCH /notes/:id - did update the content of the note (133ms)
[33mtests_1  |[0m   ✔ 1-golden-path › DELETE /notes/:id - returns a null error (132ms)
[33mtests_1  |[0m   ✔ 1-golden-path › DELETE /notes/:id - returns a status 200 (129ms)
[33mtests_1  |[0m   ✔ 1-golden-path › DELETE /notes/:id - did delete the note (140ms)
[33mtests_1  |[0m ℹ️ Testing API in end-to-end mode.
[33mtests_1  |[0m WARNING: These tests will clear the database mongodb://mongo:27017
[36mapi_1    |[0m 15:52:45 0|server  | TypeError: Cannot destructure property 'username' of 'req.body' as it is undefined.
[36mapi_1    |[0m 15:52:45 0|server  |     at /home/node/app/server.js:18:13
[36mapi_1    |[0m 15:52:45 0|server  |     at nextTick (/home/node/app/node_modules/restify/lib/chain.js:167:13)
[36mapi_1    |[0m 15:52:45 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signup without password - returns an error Rejected promise returned by test
[36mapi_1    |[0m 15:52:50 0|server  | TypeError: Cannot destructure property 'username' of 'req.body' as it is undefined.
[36mapi_1    |[0m 15:52:50 0|server  |     at /home/node/app/server.js:18:13
[36mapi_1    |[0m 15:52:50 0|server  |     at nextTick (/home/node/app/node_modules/restify/lib/chain.js:167:13)
[36mapi_1    |[0m 15:52:50 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signup without password - returns a status 400 Rejected promise returned by test
[36mapi_1    |[0m 15:52:55 0|server  | TypeError: Cannot destructure property 'username' of 'req.body' as it is undefined.
[36mapi_1    |[0m 15:52:55 0|server  |     at /home/node/app/server.js:18:13
[36mapi_1    |[0m 15:52:55 0|server  |     at nextTick (/home/node/app/node_modules/restify/lib/chain.js:167:13)
[36mapi_1    |[0m 15:52:55 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signup without password - returns no token Rejected promise returned by test
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signup without username - returns an error 
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup without username - returns a status 400
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup without username - returns no token
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup with invalid username - returns an error
[36mapi_1    |[0m 15:53:02 0|server  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.setHeader (_http_outgoing.js:526:11)
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.__send (/home/node/app/node_modules/restify/lib/response.js:505:18)
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.send (/home/node/app/node_modules/restify/lib/response.js:316:21)
[36mapi_1    |[0m 15:53:02 0|server  |     at /home/node/app/server.js:29:20
[36mapi_1    |[0m 15:53:02 0|server  |     at Object.UserController.signup (/home/node/app/controllers/user-controller.js:44:10)
[36mapi_1    |[0m 15:53:02 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[36mapi_1    |[0m 15:53:02 0|server  |   code: 'ERR_HTTP_HEADERS_SENT'
[36mapi_1    |[0m 15:53:02 0|server  | }
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup with invalid username - returns a status 400 (101ms)
[36mapi_1    |[0m 15:53:02 0|server  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.setHeader (_http_outgoing.js:526:11)
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.__send (/home/node/app/node_modules/restify/lib/response.js:505:18)
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.send (/home/node/app/node_modules/restify/lib/response.js:316:21)
[36mapi_1    |[0m 15:53:02 0|server  |     at /home/node/app/server.js:29:20
[36mapi_1    |[0m 15:53:02 0|server  |     at Object.UserController.signup (/home/node/app/controllers/user-controller.js:44:10)
[36mapi_1    |[0m 15:53:02 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[36mapi_1    |[0m 15:53:02 0|server  |   code: 'ERR_HTTP_HEADERS_SENT'
[36mapi_1    |[0m 15:53:02 0|server  | }
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup with invalid username - returns no token
[36mapi_1    |[0m 15:53:02 0|server  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.setHeader (_http_outgoing.js:526:11)
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.__send (/home/node/app/node_modules/restify/lib/response.js:505:18)
[36mapi_1    |[0m 15:53:02 0|server  |     at ServerResponse.send (/home/node/app/node_modules/restify/lib/response.js:316:21)
[36mapi_1    |[0m 15:53:02 0|server  |     at /home/node/app/server.js:29:20
[36mapi_1    |[0m 15:53:02 0|server  |     at Object.UserController.signup (/home/node/app/controllers/user-controller.js:44:10)
[36mapi_1    |[0m 15:53:02 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[36mapi_1    |[0m 15:53:02 0|server  |   code: 'ERR_HTTP_HEADERS_SENT'
[36mapi_1    |[0m 15:53:02 0|server  | }
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup with username that already exists - returns an error (178ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup with username that already exists - returns a status 400 (118ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signup with username that already exists - returns no token (119ms)
[36mapi_1    |[0m 15:53:03 0|server  | TypeError: Cannot destructure property 'username' of 'req.body' as it is undefined.
[36mapi_1    |[0m 15:53:03 0|server  |     at /home/node/app/server.js:39:13
[36mapi_1    |[0m 15:53:03 0|server  |     at nextTick (/home/node/app/node_modules/restify/lib/chain.js:167:13)
[36mapi_1    |[0m 15:53:03 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signin without password - returns an error Rejected promise returned by test
[36mapi_1    |[0m 2021-04-26T15:53:03: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
[36mapi_1    |[0m 15:53:03 PM2       | App [server:0] exited with code [1] via signal [SIGINT]
[36mapi_1    |[0m 2021-04-26T15:53:03: PM2 log: App [server:0] starting in -fork mode-
[36mapi_1    |[0m 15:53:03 PM2       | App [server:0] starting in -fork mode-
[36mapi_1    |[0m 2021-04-26T15:53:03: PM2 log: App [server:0] online
[36mapi_1    |[0m 15:53:03 PM2       | App [server:0] online
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signin without password - returns a status 400 Rejected promise returned by test
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signin without password - returns no token Rejected promise returned by test
[33mtests_1  |[0m   ✖ 2-failure-cases › POST /signin without username - returns an error Rejected promise returned by test
[36mapi_1    |[0m 15:53:10 0|server  | Successfully connected to MongoDB client
[36mapi_1    |[0m 15:53:10 0|server  | App listening on PORT 3000
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin without username - returns a status 400
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin without username - returns no token
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with invalid username - returns an error
[36mapi_1    |[0m 15:53:11 0|server  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.setHeader (_http_outgoing.js:526:11)
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.__send (/home/node/app/node_modules/restify/lib/response.js:505:18)
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.send (/home/node/app/node_modules/restify/lib/response.js:316:21)
[36mapi_1    |[0m 15:53:11 0|server  |     at /home/node/app/server.js:46:22
[36mapi_1    |[0m 15:53:11 0|server  |     at Object.UserController.signin (/home/node/app/controllers/user-controller.js:78:10)
[36mapi_1    |[0m 15:53:11 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[36mapi_1    |[0m 15:53:11 0|server  |   code: 'ERR_HTTP_HEADERS_SENT'
[36mapi_1    |[0m 15:53:11 0|server  | }
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with invalid username - returns a status 400
[36mapi_1    |[0m 15:53:11 0|server  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.setHeader (_http_outgoing.js:526:11)
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.__send (/home/node/app/node_modules/restify/lib/response.js:505:18)
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.send (/home/node/app/node_modules/restify/lib/response.js:316:21)
[36mapi_1    |[0m 15:53:11 0|server  |     at /home/node/app/server.js:46:22
[36mapi_1    |[0m 15:53:11 0|server  |     at Object.UserController.signin (/home/node/app/controllers/user-controller.js:78:10)
[36mapi_1    |[0m 15:53:11 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[36mapi_1    |[0m 15:53:11 0|server  |   code: 'ERR_HTTP_HEADERS_SENT'
[36mapi_1    |[0m 15:53:11 0|server  | }
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with invalid username - returns no token
[36mapi_1    |[0m 15:53:11 0|server  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.setHeader (_http_outgoing.js:526:11)
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.__send (/home/node/app/node_modules/restify/lib/response.js:505:18)
[36mapi_1    |[0m 15:53:11 0|server  |     at ServerResponse.send (/home/node/app/node_modules/restify/lib/response.js:316:21)
[36mapi_1    |[0m 15:53:11 0|server  |     at /home/node/app/server.js:46:22
[36mapi_1    |[0m 15:53:11 0|server  |     at Object.UserController.signin (/home/node/app/controllers/user-controller.js:78:10)
[36mapi_1    |[0m 15:53:11 0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[36mapi_1    |[0m 15:53:11 0|server  |   code: 'ERR_HTTP_HEADERS_SENT'
[36mapi_1    |[0m 15:53:11 0|server  | }
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with wrong username - returns an error (129ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with wrong username - returns a status 403 (108ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with wrong username - returns no token (108ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with wrong password - returns an error (116ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with wrong password - returns a status 403 (131ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › POST /signin with wrong password - returns no token (225ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › GET /notes without token - returns a status 401
[33mtests_1  |[0m   ✔ 2-failure-cases › GET /notes with invalid token - returns a status 401
[33mtests_1  |[0m   ✔ 2-failure-cases › GET /notes with expired token - returns a status 401
[33mtests_1  |[0m   ✔ 2-failure-cases › PUT /notes with expired token - returns a status 401
[33mtests_1  |[0m   ✔ 2-failure-cases › PATCH /notes/:id with invalid token - returns a status 401
[33mtests_1  |[0m   ✔ 2-failure-cases › PATCH /notes/:id with unknown note id - returns an error (143ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › PATCH /notes/:id with unknown note id - returns a status 404 (127ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › PATCH /notes/:id with note that belongs to another user - returns an error (258ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › PATCH /notes/:id with note that belongs to another user - returns a status 403 (260ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › DELETE /notes/:id with invalid token - returns a status 401
[33mtests_1  |[0m   ✔ 2-failure-cases › DELETE /notes/:id with unknown note id - returns an error (108ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › DELETE /notes/:id with unknown note id - returns a status 404 (106ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › DELETE /notes/:id with note that belongs to another user - returns an error (451ms)
[33mtests_1  |[0m   ✔ 2-failure-cases › DELETE /notes/:id with note that belongs to another user - returns a status 403 (345ms)
[33mtests_1  |[0m   ─
[33mtests_1  |[0m 
[33mtests_1  |[0m   1-golden-path › POST /signin on an existing user - returns a token
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/1-golden-path.test.js:48
[33mtests_1  |[0m 
[33mtests_1  |[0m    47:   });                                                                    
[33mtests_1  |[0m    48:   test('returns a token', (t, res) => t.is(typeof res.data.token, 'strin…
[33mtests_1  |[0m    49:   test('returns a null error', (t, res) => t.is(res.data.error, null));  
[33mtests_1  |[0m 
[33mtests_1  |[0m   Difference:
[33mtests_1  |[0m 
[33mtests_1  |[0m   - 'undefined'
[33mtests_1  |[0m   + 'string'
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/1-golden-path.test.js:48:41
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   1-golden-path › POST /signin on an existing user - returns a null error
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/1-golden-path.test.js:49
[33mtests_1  |[0m 
[33mtests_1  |[0m    48:   test('returns a token', (t, res) => t.is(typeof res.data.token, 'strin…
[33mtests_1  |[0m    49:   test('returns a null error', (t, res) => t.is(res.data.error, null));  
[33mtests_1  |[0m    50:   test('returns a status 200', (t, res) => t.is(res.status, 200));       
[33mtests_1  |[0m 
[33mtests_1  |[0m   Difference:
[33mtests_1  |[0m 
[33mtests_1  |[0m   - 'Cet identifiant est inconnu'
[33mtests_1  |[0m   + null
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/1-golden-path.test.js:49:46
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   1-golden-path › POST /signin on an existing user - returns a status 200
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/1-golden-path.test.js:50
[33mtests_1  |[0m 
[33mtests_1  |[0m    49:   test('returns a null error', (t, res) => t.is(res.data.error, null));
[33mtests_1  |[0m    50:   test('returns a status 200', (t, res) => t.is(res.status, 200));     
[33mtests_1  |[0m    51: });                                                                    
[33mtests_1  |[0m 
[33mtests_1  |[0m   Difference:
[33mtests_1  |[0m 
[33mtests_1  |[0m   - 403
[33mtests_1  |[0m   + 200
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/1-golden-path.test.js:50:46
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signup without password - returns an error
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:22
[33mtests_1  |[0m 
[33mtests_1  |[0m    21:   setup((t) => axios.post(`${t.context.urlPrefix}/signup`));             
[33mtests_1  |[0m    22:   test('returns an error', (t, res) => t.is(res.data.error, 'Le mot de p…
[33mtests_1  |[0m    23:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m 
[33mtests_1  |[0m   Rejected promise returned by test. Reason:
[33mtests_1  |[0m 
[33mtests_1  |[0m   TypeError {
[33mtests_1  |[0m     message: 'Cannot read property \'data\' of undefined',
[33mtests_1  |[0m   }
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:22:49
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signup without password - returns a status 400
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:23
[33mtests_1  |[0m 
[33mtests_1  |[0m    22:   test('returns an error', (t, res) => t.is(res.data.error, 'Le mot de p…
[33mtests_1  |[0m    23:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m    24:   test('returns no token', (t, res) => t.is(typeof res.data.token, 'unde…
[33mtests_1  |[0m 
[33mtests_1  |[0m   Rejected promise returned by test. Reason:
[33mtests_1  |[0m 
[33mtests_1  |[0m   TypeError {
[33mtests_1  |[0m     message: 'Cannot read property \'status\' of undefined',
[33mtests_1  |[0m   }
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:23:53
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signup without password - returns no token
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:24
[33mtests_1  |[0m 
[33mtests_1  |[0m    23:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m    24:   test('returns no token', (t, res) => t.is(typeof res.data.token, 'unde…
[33mtests_1  |[0m    25: });                                                                      
[33mtests_1  |[0m 
[33mtests_1  |[0m   Rejected promise returned by test. Reason:
[33mtests_1  |[0m 
[33mtests_1  |[0m   TypeError {
[33mtests_1  |[0m     message: 'Cannot read property \'data\' of undefined',
[33mtests_1  |[0m   }
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:24:56
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signup without username - returns an error
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:29
[33mtests_1  |[0m 
[33mtests_1  |[0m    28:   setup((t) => axios.post(`${t.context.urlPrefix}/signup`, { password: '…
[33mtests_1  |[0m    29:   test('returns an error', (t, res) => t.is(res.data.error, 'Votre ident…
[33mtests_1  |[0m    30:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m 
[33mtests_1  |[0m   Difference:
[33mtests_1  |[0m 
[33mtests_1  |[0m   - 'Saisissez un identifiant et un mot de passe'
[33mtests_1  |[0m   + 'Votre identifiant doit contenir entre 2 et 20 caractères'
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:29:42
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signin without password - returns an error
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:57
[33mtests_1  |[0m 
[33mtests_1  |[0m    56:   setup((t) => axios.post(`${t.context.urlPrefix}/signin`));             
[33mtests_1  |[0m    57:   test('returns an error', (t, res) => t.is(res.data.error, 'Le mot de p…
[33mtests_1  |[0m    58:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m 
[33mtests_1  |[0m   Rejected promise returned by test. Reason:
[33mtests_1  |[0m 
[33mtests_1  |[0m   TypeError {
[33mtests_1  |[0m     message: 'Cannot read property \'data\' of undefined',
[33mtests_1  |[0m   }
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:57:49
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signin without password - returns a status 400
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:58
[33mtests_1  |[0m 
[33mtests_1  |[0m    57:   test('returns an error', (t, res) => t.is(res.data.error, 'Le mot de p…
[33mtests_1  |[0m    58:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m    59:   test('returns no token', (t, res) => t.is(typeof res.data.token, 'unde…
[33mtests_1  |[0m 
[33mtests_1  |[0m   Rejected promise returned by test. Reason:
[33mtests_1  |[0m 
[33mtests_1  |[0m   TypeError {
[33mtests_1  |[0m     message: 'Cannot read property \'status\' of undefined',
[33mtests_1  |[0m   }
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:58:53
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signin without password - returns no token
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:59
[33mtests_1  |[0m 
[33mtests_1  |[0m    58:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m    59:   test('returns no token', (t, res) => t.is(typeof res.data.token, 'unde…
[33mtests_1  |[0m    60: });                                                                      
[33mtests_1  |[0m 
[33mtests_1  |[0m   Rejected promise returned by test. Reason:
[33mtests_1  |[0m 
[33mtests_1  |[0m   TypeError {
[33mtests_1  |[0m     message: 'Cannot read property \'data\' of undefined',
[33mtests_1  |[0m   }
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:59:56
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m 
[33mtests_1  |[0m   2-failure-cases › POST /signin without username - returns an error
[33mtests_1  |[0m 
[33mtests_1  |[0m   tests/2-failure-cases.test.js:64
[33mtests_1  |[0m 
[33mtests_1  |[0m    63:   setup((t) => axios.post(`${t.context.urlPrefix}/signin`, { password: '…
[33mtests_1  |[0m    64:   test('returns an error', (t, res) => t.is(res.data.error, 'Votre ident…
[33mtests_1  |[0m    65:   test('returns a status 400', (t, res) => t.is(res.status, 400));       
[33mtests_1  |[0m 
[33mtests_1  |[0m   Rejected promise returned by test. Reason:
[33mtests_1  |[0m 
[33mtests_1  |[0m   TypeError {
[33mtests_1  |[0m     message: 'Cannot read property \'data\' of undefined',
[33mtests_1  |[0m   }
[33mtests_1  |[0m 
[33mtests_1  |[0m   › tests/2-failure-cases.test.js:64:49
[33mtests_1  |[0m   › tests/setup/common.js:41:12
[33mtests_1  |[0m 
[33mtests_1  |[0m   ─
[33mtests_1  |[0m 
[33mtests_1  |[0m   11 tests failed
[33mapi-note_tests_1 exited with code 1
[0m